[package]
name = "wormhole-aggregator"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
plonky2 = { workspace = true }
wormhole-prover = { path = "../prover", default-features = false }
wormhole-verifier = { path = "../verifier", default-features = false }
wormhole-circuit = { path = "../circuit", default-features = false }
zk-circuits-common = { path = "../../common" }
rayon = { version = "1.10.0", optional = true }

[dev-dependencies]
criterion = { workspace = true }

[features]
default = ["std", "multithread"]
std = [
  "anyhow/std",
  "plonky2/std",
  "wormhole-prover/std",
  "wormhole-verifier/std",
  "zk-circuits-common/std",
]
no_std = []
no_zk = []
multithread = ["rayon"]

[lints]
workspace = true

[[bench]]
name = "aggregator"
harness = false
